markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Roxanne Dubois
url: http://roxdubois.github.io
description: Écrits | Writings 
twitter: roxannedubois
github: roxdubois
gravatar_url: 
