markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Roxanne Dubois
url: http://roxdubois.github.io
description: Écrits | Writings 
twitter: roxannedubois
github: roxdubois
gravatar_url:  http://www.gravatar.com/avatar/65362c40a637216a6903bd61425ed9e3.jpg?d=identicon
